/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.action;

import hibernate.Customer;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.hzs.hibernate.db.HibernateSessionFactory;
import com.hzs.struts.form.AddNewCustomerForm;


public class AddNewCustomerAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		AddNewCustomerForm addNewCustomerForm = (AddNewCustomerForm) form;

		String customerId = addNewCustomerForm.getCustomerId();
		String customerName = addNewCustomerForm.getCustomerName();
		String shippingAddress = addNewCustomerForm.getShippingAddress();
		String mobile = addNewCustomerForm.getMobile();
		String customerClass = addNewCustomerForm.getCustomerClass();
		String buildDate = addNewCustomerForm.getBuildDate();

		Customer customer = new Customer(customerId, customerName,
				shippingAddress, mobile, customerClass, buildDate);

		Session session = HibernateSessionFactory.getSession();
		Transaction tx = session.beginTransaction();

		session.save(customer);
		session.flush();
		session.clear();

		tx.commit();

		return mapping.findForward("addNewCustomer");
	}
}