/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.hzs.hibernate.db.HibernateSessionFactory;
import com.hzs.struts.form.ManAddTimetableForm;
import com.myeclipse.hibernate.Course;
import com.myeclipse.hibernate.Teacher;
import com.myeclipse.hibernate.Timetable;

public class ManAddTimetableAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		ManAddTimetableForm manAddTimetableForm = (ManAddTimetableForm) form;// TODO Auto-generated method stub
		
		//get manager input timetable info
		Teacher t = new Teacher();
		t.setWorkNum(Integer.parseInt(manAddTimetableForm.getWorkNum()));
		
		Course c = new Course();
		c.setId(Integer.parseInt(manAddTimetableForm.getCourseID()));
		
		int termNum = Integer.parseInt(manAddTimetableForm.getTermID());
		int classId = Integer.parseInt(manAddTimetableForm.getClassID());
		String room = manAddTimetableForm.getRoom();
		int beginWeek = Integer.parseInt(manAddTimetableForm.getBeginWeek());
		int endWeek = Integer.parseInt(manAddTimetableForm.getEndWeek());
		int beginCourse = Integer.parseInt(manAddTimetableForm.getBeginCourse());
		int endCourse = Integer.parseInt(manAddTimetableForm.getEndCourse());
		
		//hibernate insert a new record
		Timetable timetable = new Timetable(c, t, termNum, classId, room, beginWeek, endWeek, beginCourse, endCourse);
		
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		
		session.save(timetable);
		session.flush();
		session.clear();
		
		tx.commit();
		
		return mapping.findForward("managerWeb");
	}
}