/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.hzs.hibernate.db.HibernateSessionFactory;
import com.hzs.struts.form.ModifyPwdForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2014
 * 
 * XDoclet definition:
 * @struts.action path="/modifyPwd" name="modifyPwdForm" input="/form/modifyPwd.jsp" scope="request"
 */
public class ModifyPwdAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		ModifyPwdForm modifyPwdForm = (ModifyPwdForm) form;// TODO Auto-generated method stub
		
		String realID = (String)request.getSession().getAttribute("RealID");
		
		//hql update
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		
		Query query = session.createQuery("update User u set u.password = ? where u.id = ?");
		query.setString(0, modifyPwdForm.getNewPwd());
		query.setInteger(1, Integer.parseInt(realID));
		query.executeUpdate();
		
		tx.commit();
		
		return mapping.findForward("userLogin");
	}
}