/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.hzs.hibernate.db.HibernateSessionFactory;
import com.hzs.struts.form.ModTimetableForm;
import com.myeclipse.hibernate.Course;
import com.myeclipse.hibernate.Teacher;
import com.myeclipse.hibernate.Timetable;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2014
 * 
 * XDoclet definition:
 * @struts.action path="/modTimetable" name="modTimetableForm" input="/form/modTimetable.jsp" scope="request"
 */
public class ModTimetableAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		ModTimetableForm modTimetableForm = (ModTimetableForm) form;// TODO Auto-generated method stub
		
		//waiting to modify this object
		Timetable modTimetable = (Timetable)request.getSession().getAttribute("ModItem");
		
		//get modify input
		int termNum = modTimetableForm.getTermNum();
		int workNum = modTimetableForm.getWorkNum();
		int classId = modTimetableForm.getClassID();
		String room = modTimetableForm.getRoom();
		int courseNum = modTimetableForm.getCourseNum();
		int beginWeek = modTimetableForm.getBeginWeek();
		int endWeek = modTimetableForm.getEndWeek();
		int beginCourse = modTimetableForm.getBeginCourse();
		int endCourse = modTimetableForm.getEndCourse();
		
		//construct new object
		Teacher t = new Teacher();
		t.setWorkNum(workNum);
		
		Course c = new Course();
		c.setId(courseNum);
		
		
		//hibernate query db
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		
		Timetable timetable = new Timetable(c, t, termNum, classId, room, beginWeek, endWeek, beginCourse, endCourse);
		timetable.setTtid(modTimetable.getTtid());
		
		//kill previous modTimetable else will lead to exception
		session.evict(modTimetable);
		
		session.update(timetable);
		session.flush();
		
		tx.commit();
		
		return mapping.findForward("manModDelTimetable");
	}
}