/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.hzs.hibernate.db.HibernateSessionFactory;
import com.hzs.struts.form.StudentWebForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * @struts.action path="/studentWeb" name="studentWebForm" input="/form/studentWeb.jsp" scope="request"
 */
public class StudentWebAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		StudentWebForm studentWebForm = (StudentWebForm) form;// TODO Auto-generated method stub
		
	    String choice = studentWebForm.getChoice();
	    
	    if (choice.equals("1")) { //query personal information
	    	return mapping.findForward("stuBasicInfo");
	    }
	    else if (choice.equals("2")){ //modify personal information
	    	//hibernate query for show info
	    	String realID = (String)request.getSession().getAttribute("RealID");
	    	
	    	Session session = HibernateSessionFactory.getSession();
	    	Transaction tx = session.beginTransaction();
	    	
	    	//clear buffer
	    	session.clear();
	    	
	    	Query query = session.createQuery("select new Student(s.classId, s.email, s.phoneNum) from Student s where s.stuNum = ?");
	    	query.setInteger(0, Integer.parseInt(realID));
	    	
	    	List list = query.list();
	    	
	    	request.getSession().setAttribute("StuInfo", list.get(0));
	    	
	    	return mapping.findForward("stuModifyInfo");
	    }
	    else if (choice.equals("3")) { //query timetable
	    	return mapping.findForward("stuTimetable");
	    }
	    
		return null;
	}
}