/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.hzs.hibernate.db.HibernateSessionFactory;
import com.hzs.struts.form.StuModifyInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * @struts.action path="/stuBasicInfo" name="stuBasicInfoForm" input="/form/stuBasicInfo.jsp" scope="request"
 */
public class StuModifyInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		StuModifyInfoForm stuBasicInfoForm = (StuModifyInfoForm) form;// TODO Auto-generated method stub
		
		String ClassID = stuBasicInfoForm.getClassID();
		String Email = stuBasicInfoForm.getEmail();
		String PhoneNum = stuBasicInfoForm.getPhoneNumber();
		
		//get RealID
		HttpSession servletSession = request.getSession();
		String RealID = (String)servletSession.getAttribute("RealID");
		
		//modify corresponding property
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		
		//get old class
		//Student old = new Student();
		//old = (Student)session.get(Student.class, Integer.parseInt(RealID));
		
		//set new value
		//old.setClassId(Integer.parseInt(ClassID));
		//old.setEmail(Email);
		//old.setPhoneNum(Integer.parseInt(PhoneNum));
		
		//update
		//session.update(old);
		
		Query query = session.createQuery("update Student s set s.classId = ?, s.email = ?, s.phoneNum = ? where s.stuNum = ?");
		query.setInteger(0, Integer.parseInt(ClassID));
		query.setString(1, Email);
		query.setInteger(2, Integer.parseInt(PhoneNum));
		query.setInteger(3, Integer.parseInt(RealID));
		
		query.executeUpdate();
		tx.commit();
		
		return mapping.findForward("studentWeb");
	}
}