/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.hzs.hibernate.db.HibernateSessionFactory;
import com.hzs.struts.form.TeacherWebForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2014
 * 
 * XDoclet definition:
 * @struts.action path="/teacherWeb" name="teacherWebForm" input="/form/teacherWeb.jsp" scope="request"
 */
public class TeacherWebAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		TeacherWebForm teacherWebForm = (TeacherWebForm) form;// TODO Auto-generated method stub
		
		String choice = teacherWebForm.getChoice();
	    
	    if (choice.equals("1")) { //query personal information
	    	return mapping.findForward("teaBasicInfo");
	    }
	    else if (choice.equals("2")){ //modify personal information
	    	//hibernate query for show info
	    	String realID = (String)request.getSession().getAttribute("RealID");
	    	
	    	Session session = HibernateSessionFactory.getSession();
	    	Transaction tx = session.beginTransaction();
	    	
	    	//clear buffer
	    	session.clear();
	    	
	    	Query query = session.createQuery("select new Teacher(t.school, t.email, t.phoneNum) from Teacher t where t.workNum = ?");
	    	query.setInteger(0, Integer.parseInt(realID));
	    	
	    	List list = query.list();
	    	
	    	request.getSession().setAttribute("TeaInfo", list.get(0));
	    	
	    	return mapping.findForward("teaModifyInfo");
	    }
	    else if (choice.equals("3")) { //query timetable
	    	return mapping.findForward("teaTimetable");
	    }
	    
		return null;
	}
}