/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2014
 * 
 * XDoclet definition:
 * @struts.form name="manModDelTimetableForm"
 */
public class ManModDelTimetableForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** recordNum property */
	private int recordNum;

	/** function property */
	private int function;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the recordNum.
	 * @return String
	 */
	public int getRecordNum() {
		return recordNum;
	}

	/** 
	 * Set the recordNum.
	 * @param recordNum The recordNum to set
	 */
	public void setRecordNum(int recordNum) {
		this.recordNum = recordNum;
	}

	/** 
	 * Returns the function.
	 * @return int
	 */
	public int getFunction() {
		return function;
	}

	/** 
	 * Set the function.
	 * @param function The function to set
	 */
	public void setFunction(int function) {
		this.function = function;
	}
}