/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2014
 * 
 * XDoclet definition:
 * @struts.form name="modifyPwdForm"
 */
public class ModifyPwdForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** newPwd property */
	private String newPwd;


	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the newPwd.
	 * @return String
	 */
	public String getNewPwd() {
		return newPwd;
	}

	/** 
	 * Set the newPwd.
	 * @param newPwd The newPwd to set
	 */
	public void setNewPwd(String newPwd) {
		this.newPwd = newPwd;
	}
}