/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2014
 * 
 * XDoclet definition:
 * @struts.form name="modTimetableForm"
 */
public class ModTimetableForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** termNum property */
	private int termNum;

	/** beginCourse property */
	private int beginCourse;

	/** classID property */
	private int classID;

	/** endCourse property */
	private int endCourse;

	/** endWeek property */
	private int endWeek;

	/** beginWeek property */
	private int beginWeek;

	/** teacherName property */
	private int workNum;

	/** courseName property */
	private int courseNum;

	/** room property */
	private String room;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the termNum.
	 * @return int
	 */
	public int getTermNum() {
		return termNum;
	}

	/** 
	 * Set the termNum.
	 * @param termNum The termNum to set
	 */
	public void setTermNum(int termNum) {
		this.termNum = termNum;
	}

	/** 
	 * Returns the beginCourse.
	 * @return int
	 */
	public int getBeginCourse() {
		return beginCourse;
	}

	/** 
	 * Set the beginCourse.
	 * @param beginCourse The beginCourse to set
	 */
	public void setBeginCourse(int beginCourse) {
		this.beginCourse = beginCourse;
	}

	/** 
	 * Returns the classID.
	 * @return int
	 */
	public int getClassID() {
		return classID;
	}

	/** 
	 * Set the classID.
	 * @param classID The classID to set
	 */
	public void setClassID(int classID) {
		this.classID = classID;
	}

	/** 
	 * Returns the endCourse.
	 * @return int
	 */
	public int getEndCourse() {
		return endCourse;
	}

	/** 
	 * Set the endCourse.
	 * @param endCourse The endCourse to set
	 */
	public void setEndCourse(int endCourse) {
		this.endCourse = endCourse;
	}

	/** 
	 * Returns the endWeek.
	 * @return int
	 */
	public int getEndWeek() {
		return endWeek;
	}

	/** 
	 * Set the endWeek.
	 * @param endWeek The endWeek to set
	 */
	public void setEndWeek(int endWeek) {
		this.endWeek = endWeek;
	}

	/** 
	 * Returns the beginWeek.
	 * @return int
	 */
	public int getBeginWeek() {
		return beginWeek;
	}

	/** 
	 * Set the beginWeek.
	 * @param beginWeek The beginWeek to set
	 */
	public void setBeginWeek(int beginWeek) {
		this.beginWeek = beginWeek;
	}

	/** 
	 * Returns the teacherName.
	 * @return String
	 */
	public int getWorkNum() {
		return workNum;
	}

	/** 
	 * Set the teacherName.
	 * @param teacherName The teacherName to set
	 */
	public void setWorkNum(int workNum) {
		this.workNum = workNum;
	}

	/** 
	 * Returns the courseName.
	 * @return String
	 */
	public int getCourseNum() {
		return courseNum;
	}

	/** 
	 * Set the courseName.
	 * @param courseName The courseName to set
	 */
	public void setCourseNum(int courseNum) {
		this.courseNum = courseNum;
	}

	/** 
	 * Returns the room.
	 * @return String
	 */
	public String getRoom() {
		return room;
	}

	/** 
	 * Set the room.
	 * @param room The room to set
	 */
	public void setRoom(String room) {
		this.room = room;
	}
}