/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * @struts.form name="studentWebForm"
 */
public class StudentWebForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** choice property */
	private String choice;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the choice.
	 * @return String
	 */
	public String getChoice() {
		return choice;
	}

	/** 
	 * Set the choice.
	 * @param choice The choice to set
	 */
	public void setChoice(String choice) {
		this.choice = choice;
	}
}