/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * @struts.form name="teaModifyInfoForm"
 */
public class TeaModifyInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** phoneNumber property */
	private String phoneNumber;

	/** email property */
	private String email;

	/** school property */
	private String school;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the phoneNumber.
	 * @return String
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/** 
	 * Set the phoneNumber.
	 * @param phoneNumber The phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the school.
	 * @return String
	 */
	public String getSchool() {
		return school;
	}

	/** 
	 * Set the school.
	 * @param school The school to set
	 */
	public void setSchool(String school) {
		this.school = school;
	}
}