/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hzs.struts.form;

import org.apache.struts.action.ActionForm;

/**
 * MyEclipse Struts Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * 
 * @struts.form name="userLoginForm"
 */
public class UserLoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userpwd property */
	private String userpwd;

	/** username property */
	private String username;

	/*
	 * Generated Methods
	 */

	/**
	 * Returns the userpwd.
	 * 
	 * @return String
	 */
	public String getUserpwd() {
		return userpwd;
	}

	/**
	 * Set the userpwd.
	 * 
	 * @param userpwd
	 *            The userpwd to set
	 */
	public void setUserpwd(String userpwd) {
		this.userpwd = userpwd;
	}

	/**
	 * Returns the username.
	 * 
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * Set the username.
	 * 
	 * @param username
	 *            The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}